#!/bin/sh

PROC="/opt/usr/bin/ruantiblock.sh"

case "$1" in
    start|restart|stop|update|force-update|status)
        $PROC "$1"
    ;;
    *)
        echo " Usage: `basename $0` start|stop|restart|update|force-update|status"
        exit 1
    ;;
esac
